### PR TITLE
Fix Build And Update To Production Safe SDK and API

### PR DESCRIPTION
**Pull request by fleupold**
Currently running `make host` on a clean checkout doesn't work. 

The reason being that `index.html` is copied in the beginning of the makefile (at `npm run bundle`) and therefore the `index.html` target (that does the crucial replacements of style and js code) believes it has nothing more to do since `dist/index.html` already exists at this point. This leads to the Safe App loading with a blank screen (as no logic is injected).

I believe the right fix is to not copy index.html in the bundling step.

### CODE REVIEW

**Comment by nlordell** [comment]
> I believe the right fix is to not copy index.html in the bundling step.

This is reasonable to me. I think that this may be some leftover from when the `index.html` and `index.js` were distributed separately.

**Review by nlordell — APPROVED** [review]
Changes look good to me.

**Comment by nlordell** [comment]
Let me know when it is ready to merge and I can pin a new version on IPFS and update the ENS content record.

**Comment by fleupold** [comment]
Ready to merge from my side (already pinned to https://dickbut.eth.limo/)

**Pull request merged**
